#*****************************************************************************************
# Vivado (TM) v2018.2.1 (64-bit)
#
# build.tcl: Tcl script for re-creating project 'proj_02_hardware'
#
# Generated by Vivado on Thu Feb 06 22:09:27 -0800 2020
# IP Build 2289599 on Thu Jul 26 21:09:20 MDT 2018
#
# This file contains the Vivado Tcl commands for re-creating the project to the state*
# when this script was generated. In order to re-create the project, please source this
# file in the Vivado Tcl Shell.
#
# * Note that the runs in the created project will be configured the same way as the
#   original project, however they will not be launched automatically. To regenerate the
#   run results please launch the synthesis/implementation runs as needed.
#
#*****************************************************************************************
# NOTE: In order to use this script for source control purposes, please make sure that the
#       following files are added to the source control system:-
#
# 1. This project restoration tcl script (build.tcl) that was generated.
#
# 2. The following source(s) files that were local or imported into the original project.
#    (Please see the '$orig_proj_dir' and '$origin_dir' variable setting below at the start of the script)
#
#    "N:/Projects/ECE540_Proj_02/proj_02_hardware/sources/core/RAMB4K_S16.v"
#    "N:/Projects/ECE540_Proj_02/proj_02_hardware/sources/core/RAMB4K_S2.v"
#    "N:/Projects/ECE540_Proj_02/proj_02_hardware/sources/core/RAMB4K_S8.v"
#    "N:/Projects/ECE540_Proj_02/proj_02_hardware/sources/core/m14k_const.vh"
#    "N:/Projects/ECE540_Proj_02/proj_02_hardware/sources/core/m14k_config.vh"
#    "N:/Projects/ECE540_Proj_02/proj_02_hardware/sources/core/d_wsram_2k2way_xilinx.v"
#    "N:/Projects/ECE540_Proj_02/proj_02_hardware/sources/core/dataram_2k2way_xilinx.v"
#    "N:/Projects/ECE540_Proj_02/proj_02_hardware/sources/hdl/debounce.v"
#    "N:/Projects/ECE540_Proj_02/proj_02_hardware/sources/core/i_wsram_2k2way_xilinx.v"
#    "N:/Projects/ECE540_Proj_02/proj_02_hardware/sources/core/m14k_dsp_const.vh"
#    "N:/Projects/ECE540_Proj_02/proj_02_hardware/sources/core/m14k_alu_dsp_stub.v"
#    "N:/Projects/ECE540_Proj_02/proj_02_hardware/sources/core/m14k_alu_shft_32bit.v"
#    "N:/Projects/ECE540_Proj_02/proj_02_hardware/sources/core/m14k_bistctl.v"
#    "N:/Projects/ECE540_Proj_02/proj_02_hardware/sources/core/m14k_biu.v"
#    "N:/Projects/ECE540_Proj_02/proj_02_hardware/sources/core/m14k_cache_cmp.v"
#    "N:/Projects/ECE540_Proj_02/proj_02_hardware/sources/core/m14k_cache_mux.v"
#    "N:/Projects/ECE540_Proj_02/proj_02_hardware/sources/core/m14k_cdmm.v"
#    "N:/Projects/ECE540_Proj_02/proj_02_hardware/sources/core/m14k_cdmm_ctl.v"
#    "N:/Projects/ECE540_Proj_02/proj_02_hardware/sources/core/m14k_cdmm_mpustub.v"
#    "N:/Projects/ECE540_Proj_02/proj_02_hardware/sources/core/m14k_clock_buf.v"
#    "N:/Projects/ECE540_Proj_02/proj_02_hardware/sources/core/m14k_clock_nogate.v"
#    "N:/Projects/ECE540_Proj_02/proj_02_hardware/sources/core/m14k_clockandlatch.v"
#    "N:/Projects/ECE540_Proj_02/proj_02_hardware/sources/core/m14k_clockxnorgate.v"
#    "N:/Projects/ECE540_Proj_02/proj_02_hardware/sources/core/m14k_cop1_stub.v"
#    "N:/Projects/ECE540_Proj_02/proj_02_hardware/sources/core/m14k_cop2_stub.v"
#    "N:/Projects/ECE540_Proj_02/proj_02_hardware/sources/core/m14k_core.v"
#    "N:/Projects/ECE540_Proj_02/proj_02_hardware/sources/core/m14k_cp1_stub.v"
#    "N:/Projects/ECE540_Proj_02/proj_02_hardware/sources/core/m14k_cp2_stub.v"
#    "N:/Projects/ECE540_Proj_02/proj_02_hardware/sources/core/m14k_cpu.v"
#    "N:/Projects/ECE540_Proj_02/proj_02_hardware/sources/core/m14k_cpz.v"
#    "N:/Projects/ECE540_Proj_02/proj_02_hardware/sources/core/m14k_cpz_antitamper_stub.v"
#    "N:/Projects/ECE540_Proj_02/proj_02_hardware/sources/core/m14k_cpz_eicoffset_stub.v"
#    "N:/Projects/ECE540_Proj_02/proj_02_hardware/sources/core/m14k_cpz_guest_srs1.v"
#    "N:/Projects/ECE540_Proj_02/proj_02_hardware/sources/core/m14k_cpz_guest_stub.v"
#    "N:/Projects/ECE540_Proj_02/proj_02_hardware/sources/core/m14k_cpz_pc.v"
#    "N:/Projects/ECE540_Proj_02/proj_02_hardware/sources/core/m14k_cpz_pc_top.v"
#    "N:/Projects/ECE540_Proj_02/proj_02_hardware/sources/core/m14k_cpz_prid.v"
#    "N:/Projects/ECE540_Proj_02/proj_02_hardware/sources/core/m14k_cpz_root_stub.v"
#    "N:/Projects/ECE540_Proj_02/proj_02_hardware/sources/core/m14k_cpz_sps_stub.v"
#    "N:/Projects/ECE540_Proj_02/proj_02_hardware/sources/core/m14k_cpz_srs1.v"
#    "N:/Projects/ECE540_Proj_02/proj_02_hardware/sources/core/m14k_cpz_watch_stub.v"
#    "N:/Projects/ECE540_Proj_02/proj_02_hardware/sources/core/m14k_cscramble_scanio_stub.v"
#    "N:/Projects/ECE540_Proj_02/proj_02_hardware/sources/core/m14k_cscramble_stub.v"
#    "N:/Projects/ECE540_Proj_02/proj_02_hardware/sources/core/m14k_cscramble_tpl.v"
#    "N:/Projects/ECE540_Proj_02/proj_02_hardware/sources/core/m14k_dc.v"
#    "N:/Projects/ECE540_Proj_02/proj_02_hardware/sources/core/m14k_dc_bistctl.v"
#    "N:/Projects/ECE540_Proj_02/proj_02_hardware/sources/core/m14k_dcc.v"
#    "N:/Projects/ECE540_Proj_02/proj_02_hardware/sources/core/m14k_dcc_fb.v"
#    "N:/Projects/ECE540_Proj_02/proj_02_hardware/sources/core/m14k_dcc_mb_stub.v"
#    "N:/Projects/ECE540_Proj_02/proj_02_hardware/sources/core/m14k_dcc_parity_stub.v"
#    "N:/Projects/ECE540_Proj_02/proj_02_hardware/sources/core/m14k_dcc_spmb_stub.v"
#    "N:/Projects/ECE540_Proj_02/proj_02_hardware/sources/core/m14k_dcc_spstub.v"
#    "N:/Projects/ECE540_Proj_02/proj_02_hardware/sources/core/m14k_dspram_ext_stub.v"
#    "N:/Projects/ECE540_Proj_02/proj_02_hardware/sources/core/m14k_edp.v"
#    "N:/Projects/ECE540_Proj_02/proj_02_hardware/sources/core/m14k_edp_add_simple.v"
#    "N:/Projects/ECE540_Proj_02/proj_02_hardware/sources/core/m14k_edp_buf_misc_pro.v"
#    "N:/Projects/ECE540_Proj_02/proj_02_hardware/sources/core/m14k_edp_clz.v"
#    "N:/Projects/ECE540_Proj_02/proj_02_hardware/sources/core/m14k_edp_clz_16b.v"
#    "N:/Projects/ECE540_Proj_02/proj_02_hardware/sources/core/m14k_edp_clz_4b.v"
#    "N:/Projects/ECE540_Proj_02/proj_02_hardware/sources/core/m14k_ejt.v"
#    "N:/Projects/ECE540_Proj_02/proj_02_hardware/sources/core/m14k_ejt_and2.v"
#    "N:/Projects/ECE540_Proj_02/proj_02_hardware/sources/core/m14k_ejt_area.v"
#    "N:/Projects/ECE540_Proj_02/proj_02_hardware/sources/core/m14k_ejt_async_rec.v"
#    "N:/Projects/ECE540_Proj_02/proj_02_hardware/sources/core/m14k_ejt_async_snd.v"
#    "N:/Projects/ECE540_Proj_02/proj_02_hardware/sources/core/m14k_ejt_brk21.v"
#    "N:/Projects/ECE540_Proj_02/proj_02_hardware/sources/core/m14k_ejt_bus32mux2.v"
#    "N:/Projects/ECE540_Proj_02/proj_02_hardware/sources/core/m14k_ejt_dbrk.v"
#    "N:/Projects/ECE540_Proj_02/proj_02_hardware/sources/core/m14k_ejt_fifo_1r1w_stub.v"
#    "N:/Projects/ECE540_Proj_02/proj_02_hardware/sources/core/m14k_ejt_gate.v"
#    "N:/Projects/ECE540_Proj_02/proj_02_hardware/sources/core/m14k_ejt_ibrk.v"
#    "N:/Projects/ECE540_Proj_02/proj_02_hardware/sources/core/m14k_ejt_mux2.v"
#    "N:/Projects/ECE540_Proj_02/proj_02_hardware/sources/core/m14k_ejt_pdttcb_stub.v"
#    "N:/Projects/ECE540_Proj_02/proj_02_hardware/sources/core/m14k_ejt_tap.v"
#    "N:/Projects/ECE540_Proj_02/proj_02_hardware/sources/core/m14k_ejt_tap_dasam.v"
#    "N:/Projects/ECE540_Proj_02/proj_02_hardware/sources/core/m14k_ejt_tap_fdc.v"
#    "N:/Projects/ECE540_Proj_02/proj_02_hardware/sources/core/m14k_ejt_tap_pcsam.v"
#    "N:/Projects/ECE540_Proj_02/proj_02_hardware/sources/core/m14k_ejt_tck.v"
#    "N:/Projects/ECE540_Proj_02/proj_02_hardware/sources/core/m14k_ejt_tripsync.v"
#    "N:/Projects/ECE540_Proj_02/proj_02_hardware/sources/core/m14k_fpuclk1_nogate.v"
#    "N:/Projects/ECE540_Proj_02/proj_02_hardware/sources/core/m14k_gf_mux2.v"
#    "N:/Projects/ECE540_Proj_02/proj_02_hardware/sources/core/m14k_glue.v"
#    "N:/Projects/ECE540_Proj_02/proj_02_hardware/sources/core/m14k_ic.v"
#    "N:/Projects/ECE540_Proj_02/proj_02_hardware/sources/core/m14k_ic_bistctl.v"
#    "N:/Projects/ECE540_Proj_02/proj_02_hardware/sources/core/m14k_icc.v"
#    "N:/Projects/ECE540_Proj_02/proj_02_hardware/sources/core/m14k_icc_mb_stub.v"
#    "N:/Projects/ECE540_Proj_02/proj_02_hardware/sources/core/m14k_icc_parity_stub.v"
#    "N:/Projects/ECE540_Proj_02/proj_02_hardware/sources/core/m14k_icc_spmb_stub.v"
#    "N:/Projects/ECE540_Proj_02/proj_02_hardware/sources/core/m14k_icc_spstub.v"
#    "N:/Projects/ECE540_Proj_02/proj_02_hardware/sources/core/m14k_icc_umips_stub.v"
#    "N:/Projects/ECE540_Proj_02/proj_02_hardware/sources/core/m14k_ispram_ext_stub.v"
#    "N:/Projects/ECE540_Proj_02/proj_02_hardware/sources/core/m14k_mdl.v"
#    "N:/Projects/ECE540_Proj_02/proj_02_hardware/sources/core/m14k_mdl_add_simple.v"
#    "N:/Projects/ECE540_Proj_02/proj_02_hardware/sources/core/m14k_mdl_ctl.v"
#    "N:/Projects/ECE540_Proj_02/proj_02_hardware/sources/core/m14k_mdl_dp.v"
#    "N:/Projects/ECE540_Proj_02/proj_02_hardware/sources/core/m14k_mmu.vh"
#    "N:/Projects/ECE540_Proj_02/proj_02_hardware/sources/core/m14k_mmuc.v"
#    "N:/Projects/ECE540_Proj_02/proj_02_hardware/sources/core/m14k_mpc.v"
#    "N:/Projects/ECE540_Proj_02/proj_02_hardware/sources/core/m14k_mpc_ctl.v"
#    "N:/Projects/ECE540_Proj_02/proj_02_hardware/sources/core/m14k_mpc_dec.v"
#    "N:/Projects/ECE540_Proj_02/proj_02_hardware/sources/core/m14k_mpc_exc.v"
#    "N:/Projects/ECE540_Proj_02/proj_02_hardware/sources/core/m14k_rf_reg.v"
#    "N:/Projects/ECE540_Proj_02/proj_02_hardware/sources/core/m14k_rf_rngc.v"
#    "N:/Projects/ECE540_Proj_02/proj_02_hardware/sources/core/m14k_rf_stub.v"
#    "N:/Projects/ECE540_Proj_02/proj_02_hardware/sources/core/m14k_siu.v"
#    "N:/Projects/ECE540_Proj_02/proj_02_hardware/sources/core/m14k_siu_int_sync.v"
#    "N:/Projects/ECE540_Proj_02/proj_02_hardware/sources/core/m14k_spram_top.v"
#    "N:/Projects/ECE540_Proj_02/proj_02_hardware/sources/core/m14k_tlb.v"
#    "N:/Projects/ECE540_Proj_02/proj_02_hardware/sources/core/m14k_tlb_collector.v"
#    "N:/Projects/ECE540_Proj_02/proj_02_hardware/sources/core/m14k_tlb_cpy.v"
#    "N:/Projects/ECE540_Proj_02/proj_02_hardware/sources/core/m14k_tlb_ctl.v"
#    "N:/Projects/ECE540_Proj_02/proj_02_hardware/sources/core/m14k_tlb_dtlb.v"
#    "N:/Projects/ECE540_Proj_02/proj_02_hardware/sources/core/m14k_tlb_itlb.v"
#    "N:/Projects/ECE540_Proj_02/proj_02_hardware/sources/core/m14k_tlb_jtlb16.v"
#    "N:/Projects/ECE540_Proj_02/proj_02_hardware/sources/core/m14k_tlb_jtlb16entries.v"
#    "N:/Projects/ECE540_Proj_02/proj_02_hardware/sources/core/m14k_tlb_jtlb1entry.v"
#    "N:/Projects/ECE540_Proj_02/proj_02_hardware/sources/core/m14k_tlb_jtlb4entries.v"
#    "N:/Projects/ECE540_Proj_02/proj_02_hardware/sources/core/m14k_tlb_utlb.v"
#    "N:/Projects/ECE540_Proj_02/proj_02_hardware/sources/core/m14k_tlb_utlbentry.v"
#    "N:/Projects/ECE540_Proj_02/proj_02_hardware/sources/core/m14k_top.v"
#    "N:/Projects/ECE540_Proj_02/proj_02_hardware/sources/core/m14k_udi_custom.v"
#    "N:/Projects/ECE540_Proj_02/proj_02_hardware/sources/core/m14k_udi_scanio_stub.v"
#    "N:/Projects/ECE540_Proj_02/proj_02_hardware/sources/system/mfp_ahb_const.vh"
#    "N:/Projects/ECE540_Proj_02/proj_02_hardware/sources/system/mfp_ahb.v"
#    "N:/Projects/ECE540_Proj_02/proj_02_hardware/sources/system/memories/mfp_ahb_b_ram.v"
#    "N:/Projects/ECE540_Proj_02/proj_02_hardware/sources/system/mfp_ahb_gpio.v"
#    "N:/Projects/ECE540_Proj_02/proj_02_hardware/sources/system/memories/mfp_ahb_p_ram.v"
#    "N:/Projects/ECE540_Proj_02/proj_02_hardware/sources/hdl/mfp_ahb_sevenseg.v"
#    "N:/Projects/ECE540_Proj_02/proj_02_hardware/sources/hdl/mfp_ahb_sevensegdec.v"
#    "N:/Projects/ECE540_Proj_02/proj_02_hardware/sources/hdl/mfp_ahb_sevensegtimer.v"
#    "N:/Projects/ECE540_Proj_02/proj_02_hardware/sources/system/mfp_ahb_withloader.v"
#    "N:/Projects/ECE540_Proj_02/proj_02_hardware/sources/system/mfp_ejtag_reset.v"
#    "N:/Projects/ECE540_Proj_02/proj_02_hardware/sources/system/mfp_srec_parser.v"
#    "N:/Projects/ECE540_Proj_02/proj_02_hardware/sources/system/mfp_srec_parser_to_ahb_lite_bridge.v"
#    "N:/Projects/ECE540_Proj_02/proj_02_hardware/sources/system/mfp_sys.v"
#    "N:/Projects/ECE540_Proj_02/proj_02_hardware/sources/system/mfp_uart_receiver.v"
#    "N:/Projects/ECE540_Proj_02/proj_02_hardware/sources/core/mvp_cregister.v"
#    "N:/Projects/ECE540_Proj_02/proj_02_hardware/sources/core/mvp_cregister_c.v"
#    "N:/Projects/ECE540_Proj_02/proj_02_hardware/sources/core/mvp_cregister_ngc.v"
#    "N:/Projects/ECE540_Proj_02/proj_02_hardware/sources/core/mvp_cregister_s.v"
#    "N:/Projects/ECE540_Proj_02/proj_02_hardware/sources/core/mvp_cregister_wide.v"
#    "N:/Projects/ECE540_Proj_02/proj_02_hardware/sources/core/mvp_cregister_wide_tlb.v"
#    "N:/Projects/ECE540_Proj_02/proj_02_hardware/sources/core/mvp_cregister_wide_utlb.v"
#    "N:/Projects/ECE540_Proj_02/proj_02_hardware/sources/core/mvp_latchn.v"
#    "N:/Projects/ECE540_Proj_02/proj_02_hardware/sources/core/mvp_mux16.v"
#    "N:/Projects/ECE540_Proj_02/proj_02_hardware/sources/core/mvp_mux1hot_10.v"
#    "N:/Projects/ECE540_Proj_02/proj_02_hardware/sources/core/mvp_mux1hot_13.v"
#    "N:/Projects/ECE540_Proj_02/proj_02_hardware/sources/core/mvp_mux1hot_24.v"
#    "N:/Projects/ECE540_Proj_02/proj_02_hardware/sources/core/mvp_mux1hot_3.v"
#    "N:/Projects/ECE540_Proj_02/proj_02_hardware/sources/core/mvp_mux1hot_4.v"
#    "N:/Projects/ECE540_Proj_02/proj_02_hardware/sources/core/mvp_mux1hot_5.v"
#    "N:/Projects/ECE540_Proj_02/proj_02_hardware/sources/core/mvp_mux1hot_6.v"
#    "N:/Projects/ECE540_Proj_02/proj_02_hardware/sources/core/mvp_mux1hot_8.v"
#    "N:/Projects/ECE540_Proj_02/proj_02_hardware/sources/core/mvp_mux1hot_9.v"
#    "N:/Projects/ECE540_Proj_02/proj_02_hardware/sources/core/mvp_mux2.v"
#    "N:/Projects/ECE540_Proj_02/proj_02_hardware/sources/core/mvp_mux4.v"
#    "N:/Projects/ECE540_Proj_02/proj_02_hardware/sources/core/mvp_mux8.v"
#    "N:/Projects/ECE540_Proj_02/proj_02_hardware/sources/core/mvp_register.v"
#    "N:/Projects/ECE540_Proj_02/proj_02_hardware/sources/core/mvp_register_c.v"
#    "N:/Projects/ECE540_Proj_02/proj_02_hardware/sources/core/mvp_register_ngc.v"
#    "N:/Projects/ECE540_Proj_02/proj_02_hardware/sources/core/mvp_register_s.v"
#    "N:/Projects/ECE540_Proj_02/proj_02_hardware/sources/core/mvp_ucregister_wide.v"
#    "N:/Projects/ECE540_Proj_02/proj_02_hardware/sources/system/memories/ram_b0.v"
#    "N:/Projects/ECE540_Proj_02/proj_02_hardware/sources/system/memories/ram_b1.v"
#    "N:/Projects/ECE540_Proj_02/proj_02_hardware/sources/system/memories/ram_b2.v"
#    "N:/Projects/ECE540_Proj_02/proj_02_hardware/sources/system/memories/ram_b3.v"
#    "N:/Projects/ECE540_Proj_02/proj_02_hardware/sources/system/memories/ram_p0.v"
#    "N:/Projects/ECE540_Proj_02/proj_02_hardware/sources/system/memories/ram_p1.v"
#    "N:/Projects/ECE540_Proj_02/proj_02_hardware/sources/system/memories/ram_p2.v"
#    "N:/Projects/ECE540_Proj_02/proj_02_hardware/sources/system/memories/ram_p3.v"
#    "N:/Projects/ECE540_Proj_02/proj_02_hardware/sources/core/tagram_2k2way_xilinx.v"
#    "N:/Projects/ECE540_Proj_02/proj_02_hardware/sources/nexys4_ddr/mfp_nexys4_ddr.v"
#    "N:/Projects/ECE540_Proj_02/proj_02_hardware/sources/core/m14k_cdmmstub.v"
#    "N:/Projects/ECE540_Proj_02/proj_02_hardware/sources/core/m14k_edp_buf_misc.v"
#    "N:/Projects/ECE540_Proj_02/proj_02_hardware/sources/core/m14k_ejt_tap_dasamstub.v"
#    "N:/Projects/ECE540_Proj_02/proj_02_hardware/sources/core/m14k_ejt_tap_fdcstub.v"
#    "N:/Projects/ECE540_Proj_02/proj_02_hardware/sources/core/m14k_ejt_tap_pcsamstub.v"
#    "N:/Projects/ECE540_Proj_02/proj_02_hardware/sources/core/m14k_udi_stub.v"
#    "N:/Projects/ECE540_Proj_02/proj_02_hardware/sources/core/ram_dual_port.v"
#    "N:/Projects/ECE540_Proj_02/proj_02_hardware/sources/core/ram_reset_dual_port.v"
#    "N:/Projects/ECE540_Proj_02/proj_02_hardware/sources/testbench/testbench.v"
#    "N:/Projects/ECE540_Proj_02/proj_02_hardware/sources/testbench/testbench_boot.v"
#    "N:/Projects/ECE540_Proj_02/proj_02_hardware/sources/testbench/testbench_sw2led.v"
#    "N:/Projects/ECE540_Proj_02/proj_02_hardware/sources/hdl/hdl_part1/world_maps_part1/world_map.ngc"
#    "N:/Projects/ECE540_Proj_02/proj_02_hardware/sources/hdl/hdl_part1/world_maps_part1/world_map.v"
#    "N:/Projects/ECE540_Proj_02/proj_02_hardware/proj_02_hardware.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xci"
#    "n:/Projects/ECE540_Proj_02/proj_02_hardware/proj_02_hardware.srcs/sources_1/ip/clk_wiz_1/clk_wiz_1.xci"
#    "n:/Projects/ECE540_Proj_02/proj_02_hardware/proj_02_hardware.srcs/sources_1/ip/rojobot31_0/rojobot31_0.xci"
#    "N:/Projects/ECE540_Proj_02/proj_02_hardware/sources/constraints/mfp_nexys4_ddr.xdc"
#
# 3. The following remote source files that were added to the original project:-
#
#    <none>
#
#*****************************************************************************************

# Set the reference directory for source file relative paths (by default the value is script directory path)
set origin_dir "."

# Use origin directory path location variable, if specified in the tcl shell
if { [info exists ::origin_dir_loc] } {
  set origin_dir $::origin_dir_loc
}

# Set the project name
set _xil_proj_name_ "proj_02_hardware"

# Use project name variable, if specified in the tcl shell
if { [info exists ::user_project_name] } {
  set _xil_proj_name_ $::user_project_name
}

variable script_file
set script_file "build.tcl"

# Help information for this script
proc help {} {
  variable script_file
  puts "\nDescription:"
  puts "Recreate a Vivado project from this script. The created project will be"
  puts "functionally equivalent to the original project for which this script was"
  puts "generated. The script contains commands for creating a project, filesets,"
  puts "runs, adding/importing sources and setting properties on various objects.\n"
  puts "Syntax:"
  puts "$script_file"
  puts "$script_file -tclargs \[--origin_dir <path>\]"
  puts "$script_file -tclargs \[--project_name <name>\]"
  puts "$script_file -tclargs \[--help\]\n"
  puts "Usage:"
  puts "Name                   Description"
  puts "-------------------------------------------------------------------------"
  puts "\[--origin_dir <path>\]  Determine source file paths wrt this path. Default"
  puts "                       origin_dir path value is \".\", otherwise, the value"
  puts "                       that was set with the \"-paths_relative_to\" switch"
  puts "                       when this script was generated.\n"
  puts "\[--project_name <name>\] Create project with the specified name. Default"
  puts "                       name is the name of the project from where this"
  puts "                       script was generated.\n"
  puts "\[--help\]               Print help information for this script"
  puts "-------------------------------------------------------------------------\n"
  exit 0
}

if { $::argc > 0 } {
  for {set i 0} {$i < $::argc} {incr i} {
    set option [string trim [lindex $::argv $i]]
    switch -regexp -- $option {
      "--origin_dir"   { incr i; set origin_dir [lindex $::argv $i] }
      "--project_name" { incr i; set _xil_proj_name_ [lindex $::argv $i] }
      "--help"         { help }
      default {
        if { [regexp {^-} $option] } {
          puts "ERROR: Unknown option '$option' specified, please type '$script_file -tclargs --help' for usage info.\n"
          return 1
        }
      }
    }
  }
}

# Set the directory path for the original project from where this script was exported
set orig_proj_dir "[file normalize "$origin_dir/"]"

# Create project
create_project ${_xil_proj_name_} ./${_xil_proj_name_} -part xc7a100tcsg324-1

# Set the directory path for the new project
set proj_dir [get_property directory [current_project]]

# Reconstruct message rules
# None

# Set project properties
set obj [current_project]
set_property -name "board_part" -value "digilentinc.com:nexys4_ddr:part0:1.1" -objects $obj
set_property -name "default_lib" -value "xil_defaultlib" -objects $obj
set_property -name "dsa.accelerator_binary_content" -value "bitstream" -objects $obj
set_property -name "dsa.accelerator_binary_format" -value "xclbin2" -objects $obj
set_property -name "dsa.board_id" -value "nexys4_ddr" -objects $obj
set_property -name "dsa.description" -value "Vivado generated DSA" -objects $obj
set_property -name "dsa.dr_bd_base_address" -value "0" -objects $obj
set_property -name "dsa.emu_dir" -value "emu" -objects $obj
set_property -name "dsa.flash_interface_type" -value "bpix16" -objects $obj
set_property -name "dsa.flash_offset_address" -value "0" -objects $obj
set_property -name "dsa.flash_size" -value "1024" -objects $obj
set_property -name "dsa.host_architecture" -value "x86_64" -objects $obj
set_property -name "dsa.host_interface" -value "pcie" -objects $obj
set_property -name "dsa.num_compute_units" -value "60" -objects $obj
set_property -name "dsa.platform_state" -value "pre_synth" -objects $obj
set_property -name "dsa.uses_pr" -value "1" -objects $obj
set_property -name "dsa.vendor" -value "xilinx" -objects $obj
set_property -name "dsa.version" -value "0.0" -objects $obj
set_property -name "enable_vhdl_2008" -value "1" -objects $obj
set_property -name "ip_cache_permissions" -value "read write" -objects $obj
set_property -name "ip_output_repo" -value "$proj_dir/${_xil_proj_name_}.cache/ip" -objects $obj
set_property -name "mem.enable_memory_map_generation" -value "1" -objects $obj
set_property -name "sim.central_dir" -value "$proj_dir/${_xil_proj_name_}.ip_user_files" -objects $obj
set_property -name "sim.ip.auto_export_scripts" -value "1" -objects $obj
set_property -name "simulator_language" -value "Mixed" -objects $obj
set_property -name "webtalk.activehdl_export_sim" -value "3" -objects $obj
set_property -name "webtalk.ies_export_sim" -value "3" -objects $obj
set_property -name "webtalk.modelsim_export_sim" -value "3" -objects $obj
set_property -name "webtalk.questa_export_sim" -value "3" -objects $obj
set_property -name "webtalk.riviera_export_sim" -value "3" -objects $obj
set_property -name "webtalk.vcs_export_sim" -value "3" -objects $obj
set_property -name "webtalk.xcelium_export_sim" -value "2" -objects $obj
set_property -name "webtalk.xsim_export_sim" -value "3" -objects $obj
set_property -name "xpm_libraries" -value "XPM_CDC" -objects $obj

# Create 'sources_1' fileset (if not found)
if {[string equal [get_filesets -quiet sources_1] ""]} {
  create_fileset -srcset sources_1
}

# Set IP repository paths
set obj [get_filesets sources_1]
set_property "ip_repo_paths" "[file normalize "$origin_dir/sources/hdl/rojobot31"]" $obj

# Rebuild user ip_repo's index before adding any source files
update_ip_catalog -rebuild

# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
# Import local files from the original project
set files [list \
 [file normalize "${origin_dir}/sources/core/RAMB4K_S16.v" ]\
 [file normalize "${origin_dir}/sources/core/RAMB4K_S2.v" ]\
 [file normalize "${origin_dir}/sources/core/RAMB4K_S8.v" ]\
 [file normalize "${origin_dir}/sources/core/m14k_const.vh" ]\
 [file normalize "${origin_dir}/sources/core/m14k_config.vh" ]\
 [file normalize "${origin_dir}/sources/core/d_wsram_2k2way_xilinx.v" ]\
 [file normalize "${origin_dir}/sources/core/dataram_2k2way_xilinx.v" ]\
 [file normalize "${origin_dir}/sources/hdl/debounce.v" ]\
 [file normalize "${origin_dir}/sources/core/i_wsram_2k2way_xilinx.v" ]\
 [file normalize "${origin_dir}/sources/core/m14k_dsp_const.vh" ]\
 [file normalize "${origin_dir}/sources/core/m14k_alu_dsp_stub.v" ]\
 [file normalize "${origin_dir}/sources/core/m14k_alu_shft_32bit.v" ]\
 [file normalize "${origin_dir}/sources/core/m14k_bistctl.v" ]\
 [file normalize "${origin_dir}/sources/core/m14k_biu.v" ]\
 [file normalize "${origin_dir}/sources/core/m14k_cache_cmp.v" ]\
 [file normalize "${origin_dir}/sources/core/m14k_cache_mux.v" ]\
 [file normalize "${origin_dir}/sources/core/m14k_cdmm.v" ]\
 [file normalize "${origin_dir}/sources/core/m14k_cdmm_ctl.v" ]\
 [file normalize "${origin_dir}/sources/core/m14k_cdmm_mpustub.v" ]\
 [file normalize "${origin_dir}/sources/core/m14k_clock_buf.v" ]\
 [file normalize "${origin_dir}/sources/core/m14k_clock_nogate.v" ]\
 [file normalize "${origin_dir}/sources/core/m14k_clockandlatch.v" ]\
 [file normalize "${origin_dir}/sources/core/m14k_clockxnorgate.v" ]\
 [file normalize "${origin_dir}/sources/core/m14k_cop1_stub.v" ]\
 [file normalize "${origin_dir}/sources/core/m14k_cop2_stub.v" ]\
 [file normalize "${origin_dir}/sources/core/m14k_core.v" ]\
 [file normalize "${origin_dir}/sources/core/m14k_cp1_stub.v" ]\
 [file normalize "${origin_dir}/sources/core/m14k_cp2_stub.v" ]\
 [file normalize "${origin_dir}/sources/core/m14k_cpu.v" ]\
 [file normalize "${origin_dir}/sources/core/m14k_cpz.v" ]\
 [file normalize "${origin_dir}/sources/core/m14k_cpz_antitamper_stub.v" ]\
 [file normalize "${origin_dir}/sources/core/m14k_cpz_eicoffset_stub.v" ]\
 [file normalize "${origin_dir}/sources/core/m14k_cpz_guest_srs1.v" ]\
 [file normalize "${origin_dir}/sources/core/m14k_cpz_guest_stub.v" ]\
 [file normalize "${origin_dir}/sources/core/m14k_cpz_pc.v" ]\
 [file normalize "${origin_dir}/sources/core/m14k_cpz_pc_top.v" ]\
 [file normalize "${origin_dir}/sources/core/m14k_cpz_prid.v" ]\
 [file normalize "${origin_dir}/sources/core/m14k_cpz_root_stub.v" ]\
 [file normalize "${origin_dir}/sources/core/m14k_cpz_sps_stub.v" ]\
 [file normalize "${origin_dir}/sources/core/m14k_cpz_srs1.v" ]\
 [file normalize "${origin_dir}/sources/core/m14k_cpz_watch_stub.v" ]\
 [file normalize "${origin_dir}/sources/core/m14k_cscramble_scanio_stub.v" ]\
 [file normalize "${origin_dir}/sources/core/m14k_cscramble_stub.v" ]\
 [file normalize "${origin_dir}/sources/core/m14k_cscramble_tpl.v" ]\
 [file normalize "${origin_dir}/sources/core/m14k_dc.v" ]\
 [file normalize "${origin_dir}/sources/core/m14k_dc_bistctl.v" ]\
 [file normalize "${origin_dir}/sources/core/m14k_dcc.v" ]\
 [file normalize "${origin_dir}/sources/core/m14k_dcc_fb.v" ]\
 [file normalize "${origin_dir}/sources/core/m14k_dcc_mb_stub.v" ]\
 [file normalize "${origin_dir}/sources/core/m14k_dcc_parity_stub.v" ]\
 [file normalize "${origin_dir}/sources/core/m14k_dcc_spmb_stub.v" ]\
 [file normalize "${origin_dir}/sources/core/m14k_dcc_spstub.v" ]\
 [file normalize "${origin_dir}/sources/core/m14k_dspram_ext_stub.v" ]\
 [file normalize "${origin_dir}/sources/core/m14k_edp.v" ]\
 [file normalize "${origin_dir}/sources/core/m14k_edp_add_simple.v" ]\
 [file normalize "${origin_dir}/sources/core/m14k_edp_buf_misc_pro.v" ]\
 [file normalize "${origin_dir}/sources/core/m14k_edp_clz.v" ]\
 [file normalize "${origin_dir}/sources/core/m14k_edp_clz_16b.v" ]\
 [file normalize "${origin_dir}/sources/core/m14k_edp_clz_4b.v" ]\
 [file normalize "${origin_dir}/sources/core/m14k_ejt.v" ]\
 [file normalize "${origin_dir}/sources/core/m14k_ejt_and2.v" ]\
 [file normalize "${origin_dir}/sources/core/m14k_ejt_area.v" ]\
 [file normalize "${origin_dir}/sources/core/m14k_ejt_async_rec.v" ]\
 [file normalize "${origin_dir}/sources/core/m14k_ejt_async_snd.v" ]\
 [file normalize "${origin_dir}/sources/core/m14k_ejt_brk21.v" ]\
 [file normalize "${origin_dir}/sources/core/m14k_ejt_bus32mux2.v" ]\
 [file normalize "${origin_dir}/sources/core/m14k_ejt_dbrk.v" ]\
 [file normalize "${origin_dir}/sources/core/m14k_ejt_fifo_1r1w_stub.v" ]\
 [file normalize "${origin_dir}/sources/core/m14k_ejt_gate.v" ]\
 [file normalize "${origin_dir}/sources/core/m14k_ejt_ibrk.v" ]\
 [file normalize "${origin_dir}/sources/core/m14k_ejt_mux2.v" ]\
 [file normalize "${origin_dir}/sources/core/m14k_ejt_pdttcb_stub.v" ]\
 [file normalize "${origin_dir}/sources/core/m14k_ejt_tap.v" ]\
 [file normalize "${origin_dir}/sources/core/m14k_ejt_tap_dasam.v" ]\
 [file normalize "${origin_dir}/sources/core/m14k_ejt_tap_fdc.v" ]\
 [file normalize "${origin_dir}/sources/core/m14k_ejt_tap_pcsam.v" ]\
 [file normalize "${origin_dir}/sources/core/m14k_ejt_tck.v" ]\
 [file normalize "${origin_dir}/sources/core/m14k_ejt_tripsync.v" ]\
 [file normalize "${origin_dir}/sources/core/m14k_fpuclk1_nogate.v" ]\
 [file normalize "${origin_dir}/sources/core/m14k_gf_mux2.v" ]\
 [file normalize "${origin_dir}/sources/core/m14k_glue.v" ]\
 [file normalize "${origin_dir}/sources/core/m14k_ic.v" ]\
 [file normalize "${origin_dir}/sources/core/m14k_ic_bistctl.v" ]\
 [file normalize "${origin_dir}/sources/core/m14k_icc.v" ]\
 [file normalize "${origin_dir}/sources/core/m14k_icc_mb_stub.v" ]\
 [file normalize "${origin_dir}/sources/core/m14k_icc_parity_stub.v" ]\
 [file normalize "${origin_dir}/sources/core/m14k_icc_spmb_stub.v" ]\
 [file normalize "${origin_dir}/sources/core/m14k_icc_spstub.v" ]\
 [file normalize "${origin_dir}/sources/core/m14k_icc_umips_stub.v" ]\
 [file normalize "${origin_dir}/sources/core/m14k_ispram_ext_stub.v" ]\
 [file normalize "${origin_dir}/sources/core/m14k_mdl.v" ]\
 [file normalize "${origin_dir}/sources/core/m14k_mdl_add_simple.v" ]\
 [file normalize "${origin_dir}/sources/core/m14k_mdl_ctl.v" ]\
 [file normalize "${origin_dir}/sources/core/m14k_mdl_dp.v" ]\
 [file normalize "${origin_dir}/sources/core/m14k_mmu.vh" ]\
 [file normalize "${origin_dir}/sources/core/m14k_mmuc.v" ]\
 [file normalize "${origin_dir}/sources/core/m14k_mpc.v" ]\
 [file normalize "${origin_dir}/sources/core/m14k_mpc_ctl.v" ]\
 [file normalize "${origin_dir}/sources/core/m14k_mpc_dec.v" ]\
 [file normalize "${origin_dir}/sources/core/m14k_mpc_exc.v" ]\
 [file normalize "${origin_dir}/sources/core/m14k_rf_reg.v" ]\
 [file normalize "${origin_dir}/sources/core/m14k_rf_rngc.v" ]\
 [file normalize "${origin_dir}/sources/core/m14k_rf_stub.v" ]\
 [file normalize "${origin_dir}/sources/core/m14k_siu.v" ]\
 [file normalize "${origin_dir}/sources/core/m14k_siu_int_sync.v" ]\
 [file normalize "${origin_dir}/sources/core/m14k_spram_top.v" ]\
 [file normalize "${origin_dir}/sources/core/m14k_tlb.v" ]\
 [file normalize "${origin_dir}/sources/core/m14k_tlb_collector.v" ]\
 [file normalize "${origin_dir}/sources/core/m14k_tlb_cpy.v" ]\
 [file normalize "${origin_dir}/sources/core/m14k_tlb_ctl.v" ]\
 [file normalize "${origin_dir}/sources/core/m14k_tlb_dtlb.v" ]\
 [file normalize "${origin_dir}/sources/core/m14k_tlb_itlb.v" ]\
 [file normalize "${origin_dir}/sources/core/m14k_tlb_jtlb16.v" ]\
 [file normalize "${origin_dir}/sources/core/m14k_tlb_jtlb16entries.v" ]\
 [file normalize "${origin_dir}/sources/core/m14k_tlb_jtlb1entry.v" ]\
 [file normalize "${origin_dir}/sources/core/m14k_tlb_jtlb4entries.v" ]\
 [file normalize "${origin_dir}/sources/core/m14k_tlb_utlb.v" ]\
 [file normalize "${origin_dir}/sources/core/m14k_tlb_utlbentry.v" ]\
 [file normalize "${origin_dir}/sources/core/m14k_top.v" ]\
 [file normalize "${origin_dir}/sources/core/m14k_udi_custom.v" ]\
 [file normalize "${origin_dir}/sources/core/m14k_udi_scanio_stub.v" ]\
 [file normalize "${origin_dir}/sources/system/mfp_ahb_const.vh" ]\
 [file normalize "${origin_dir}/sources/system/mfp_ahb.v" ]\
 [file normalize "${origin_dir}/sources/system/memories/mfp_ahb_b_ram.v" ]\
 [file normalize "${origin_dir}/sources/system/mfp_ahb_gpio.v" ]\
 [file normalize "${origin_dir}/sources/system/memories/mfp_ahb_p_ram.v" ]\
 [file normalize "${origin_dir}/sources/hdl/mfp_ahb_sevenseg.v" ]\
 [file normalize "${origin_dir}/sources/hdl/mfp_ahb_sevensegdec.v" ]\
 [file normalize "${origin_dir}/sources/hdl/mfp_ahb_sevensegtimer.v" ]\
 [file normalize "${origin_dir}/sources/system/mfp_ahb_withloader.v" ]\
 [file normalize "${origin_dir}/sources/system/mfp_ejtag_reset.v" ]\
 [file normalize "${origin_dir}/sources/system/mfp_srec_parser.v" ]\
 [file normalize "${origin_dir}/sources/system/mfp_srec_parser_to_ahb_lite_bridge.v" ]\
 [file normalize "${origin_dir}/sources/system/mfp_sys.v" ]\
 [file normalize "${origin_dir}/sources/system/mfp_uart_receiver.v" ]\
 [file normalize "${origin_dir}/sources/core/mvp_cregister.v" ]\
 [file normalize "${origin_dir}/sources/core/mvp_cregister_c.v" ]\
 [file normalize "${origin_dir}/sources/core/mvp_cregister_ngc.v" ]\
 [file normalize "${origin_dir}/sources/core/mvp_cregister_s.v" ]\
 [file normalize "${origin_dir}/sources/core/mvp_cregister_wide.v" ]\
 [file normalize "${origin_dir}/sources/core/mvp_cregister_wide_tlb.v" ]\
 [file normalize "${origin_dir}/sources/core/mvp_cregister_wide_utlb.v" ]\
 [file normalize "${origin_dir}/sources/core/mvp_latchn.v" ]\
 [file normalize "${origin_dir}/sources/core/mvp_mux16.v" ]\
 [file normalize "${origin_dir}/sources/core/mvp_mux1hot_10.v" ]\
 [file normalize "${origin_dir}/sources/core/mvp_mux1hot_13.v" ]\
 [file normalize "${origin_dir}/sources/core/mvp_mux1hot_24.v" ]\
 [file normalize "${origin_dir}/sources/core/mvp_mux1hot_3.v" ]\
 [file normalize "${origin_dir}/sources/core/mvp_mux1hot_4.v" ]\
 [file normalize "${origin_dir}/sources/core/mvp_mux1hot_5.v" ]\
 [file normalize "${origin_dir}/sources/core/mvp_mux1hot_6.v" ]\
 [file normalize "${origin_dir}/sources/core/mvp_mux1hot_8.v" ]\
 [file normalize "${origin_dir}/sources/core/mvp_mux1hot_9.v" ]\
 [file normalize "${origin_dir}/sources/core/mvp_mux2.v" ]\
 [file normalize "${origin_dir}/sources/core/mvp_mux4.v" ]\
 [file normalize "${origin_dir}/sources/core/mvp_mux8.v" ]\
 [file normalize "${origin_dir}/sources/core/mvp_register.v" ]\
 [file normalize "${origin_dir}/sources/core/mvp_register_c.v" ]\
 [file normalize "${origin_dir}/sources/core/mvp_register_ngc.v" ]\
 [file normalize "${origin_dir}/sources/core/mvp_register_s.v" ]\
 [file normalize "${origin_dir}/sources/core/mvp_ucregister_wide.v" ]\
 [file normalize "${origin_dir}/sources/system/memories/ram_b0.v" ]\
 [file normalize "${origin_dir}/sources/system/memories/ram_b1.v" ]\
 [file normalize "${origin_dir}/sources/system/memories/ram_b2.v" ]\
 [file normalize "${origin_dir}/sources/system/memories/ram_b3.v" ]\
 [file normalize "${origin_dir}/sources/system/memories/ram_p0.v" ]\
 [file normalize "${origin_dir}/sources/system/memories/ram_p1.v" ]\
 [file normalize "${origin_dir}/sources/system/memories/ram_p2.v" ]\
 [file normalize "${origin_dir}/sources/system/memories/ram_p3.v" ]\
 [file normalize "${origin_dir}/sources/core/tagram_2k2way_xilinx.v" ]\
 [file normalize "${origin_dir}/sources/nexys4_ddr/mfp_nexys4_ddr.v" ]\
 [file normalize "${origin_dir}/sources/core/m14k_cdmmstub.v" ]\
 [file normalize "${origin_dir}/sources/core/m14k_edp_buf_misc.v" ]\
 [file normalize "${origin_dir}/sources/core/m14k_ejt_tap_dasamstub.v" ]\
 [file normalize "${origin_dir}/sources/core/m14k_ejt_tap_fdcstub.v" ]\
 [file normalize "${origin_dir}/sources/core/m14k_ejt_tap_pcsamstub.v" ]\
 [file normalize "${origin_dir}/sources/core/m14k_udi_stub.v" ]\
 [file normalize "${origin_dir}/sources/core/ram_dual_port.v" ]\
 [file normalize "${origin_dir}/sources/core/ram_reset_dual_port.v" ]\
 [file normalize "${origin_dir}/sources/testbench/testbench.v" ]\
 [file normalize "${origin_dir}/sources/testbench/testbench_boot.v" ]\
 [file normalize "${origin_dir}/sources/testbench/testbench_sw2led.v" ]\
 [file normalize "${origin_dir}/sources/hdl/hdl_part1/world_maps_part1/world_map.ngc" ]\
 [file normalize "${origin_dir}/sources/hdl/hdl_part1/world_maps_part1/world_map.v" ]\
]
set imported_files [import_files -fileset sources_1 $files]

# Set 'sources_1' fileset file properties for remote files
# None

# Set 'sources_1' fileset file properties for local files
set file "core/m14k_const.vh"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "Verilog Header" -objects $file_obj

set file "core/m14k_config.vh"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "Verilog Header" -objects $file_obj

set file "core/m14k_dsp_const.vh"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "Verilog Header" -objects $file_obj

set file "core/m14k_mmu.vh"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "Verilog Header" -objects $file_obj

set file "system/mfp_ahb_const.vh"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "Verilog Header" -objects $file_obj

set file "world_maps_part1/world_map.ngc"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "NGC" -objects $file_obj


# Set 'sources_1' fileset properties
set obj [get_filesets sources_1]
set_property -name "top" -value "mfp_nexys4_ddr" -objects $obj

# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
# Import local files from the original project
set files [list \
 [file normalize "${origin_dir}/proj_02_hardware.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xci" ]\
]
set imported_files [import_files -fileset sources_1 $files]

# Set 'sources_1' fileset file properties for remote files
# None

# Set 'sources_1' fileset file properties for local files
set file "clk_wiz_0/clk_wiz_0.xci"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "generate_files_for_reference" -value "0" -objects $file_obj
set_property -name "registered_with_manager" -value "1" -objects $file_obj
if { ![get_property "is_locked" $file_obj] } {
  set_property -name "synth_checkpoint_mode" -value "Singular" -objects $file_obj
}


# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
# Import local files from the original project
set files [list \
 [file normalize "${origin_dir}/proj_02_hardware.srcs/sources_1/ip/clk_wiz_1/clk_wiz_1.xci" ]\
]
set imported_files [import_files -fileset sources_1 $files]

# Set 'sources_1' fileset file properties for remote files
# None

# Set 'sources_1' fileset file properties for local files
set file "clk_wiz_1/clk_wiz_1.xci"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "generate_files_for_reference" -value "0" -objects $file_obj
set_property -name "registered_with_manager" -value "1" -objects $file_obj
if { ![get_property "is_locked" $file_obj] } {
  set_property -name "synth_checkpoint_mode" -value "Singular" -objects $file_obj
}


# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
# Import local files from the original project
set files [list \
 [file normalize "${origin_dir}/proj_02_hardware.srcs/sources_1/ip/rojobot31_0/rojobot31_0.xci" ]\
]
set imported_files [import_files -fileset sources_1 $files]

# Set 'sources_1' fileset file properties for remote files
# None

# Set 'sources_1' fileset file properties for local files
set file "rojobot31_0/rojobot31_0.xci"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "generate_files_for_reference" -value "0" -objects $file_obj
set_property -name "registered_with_manager" -value "1" -objects $file_obj
if { ![get_property "is_locked" $file_obj] } {
  set_property -name "synth_checkpoint_mode" -value "Singular" -objects $file_obj
}


# Create 'constrs_1' fileset (if not found)
if {[string equal [get_filesets -quiet constrs_1] ""]} {
  create_fileset -constrset constrs_1
}

# Set 'constrs_1' fileset object
set obj [get_filesets constrs_1]

# Add/Import constrs file and set constrs file properties
set file "[file normalize "$origin_dir/sources/constraints/mfp_nexys4_ddr.xdc"]"
set file_imported [import_files -fileset constrs_1 [list $file]]
set file "constraints/mfp_nexys4_ddr.xdc"
set file_obj [get_files -of_objects [get_filesets constrs_1] [list "*$file"]]
set_property -name "file_type" -value "XDC" -objects $file_obj

# Set 'constrs_1' fileset properties
set obj [get_filesets constrs_1]

# Create 'sim_1' fileset (if not found)
if {[string equal [get_filesets -quiet sim_1] ""]} {
  create_fileset -simset sim_1
}

# Set 'sim_1' fileset object
set obj [get_filesets sim_1]
# Empty (no sources present)

# Set 'sim_1' fileset properties
set obj [get_filesets sim_1]
set_property -name "top" -value "mfp_nexys4_ddr" -objects $obj
set_property -name "top_lib" -value "xil_defaultlib" -objects $obj

# Create 'synth_1' run (if not found)
if {[string equal [get_runs -quiet synth_1] ""]} {
    create_run -name synth_1 -part xc7a100tcsg324-1 -flow {Vivado Synthesis 2018} -strategy "Vivado Synthesis Defaults" -report_strategy {No Reports} -constrset constrs_1
} else {
  set_property strategy "Vivado Synthesis Defaults" [get_runs synth_1]
  set_property flow "Vivado Synthesis 2018" [get_runs synth_1]
}
set obj [get_runs synth_1]
set_property set_report_strategy_name 1 $obj
set_property report_strategy {Vivado Synthesis Default Reports} $obj
set_property set_report_strategy_name 0 $obj
# Create 'synth_1_synth_report_utilization_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs synth_1] synth_1_synth_report_utilization_0] "" ] } {
  create_report_config -report_name synth_1_synth_report_utilization_0 -report_type report_utilization:1.0 -steps synth_design -runs synth_1
}
set obj [get_report_configs -of_objects [get_runs synth_1] synth_1_synth_report_utilization_0]
if { $obj != "" } {

}
set obj [get_runs synth_1]
set_property -name "needs_refresh" -value "1" -objects $obj
set_property -name "strategy" -value "Vivado Synthesis Defaults" -objects $obj

# set the current synth run
current_run -synthesis [get_runs synth_1]

# Create 'impl_1' run (if not found)
if {[string equal [get_runs -quiet impl_1] ""]} {
    create_run -name impl_1 -part xc7a100tcsg324-1 -flow {Vivado Implementation 2018} -strategy "Vivado Implementation Defaults" -report_strategy {No Reports} -constrset constrs_1 -parent_run synth_1
} else {
  set_property strategy "Vivado Implementation Defaults" [get_runs impl_1]
  set_property flow "Vivado Implementation 2018" [get_runs impl_1]
}
set obj [get_runs impl_1]
set_property set_report_strategy_name 1 $obj
set_property report_strategy {Vivado Implementation Default Reports} $obj
set_property set_report_strategy_name 0 $obj
# Create 'impl_1_init_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_init_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_init_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps init_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_init_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj

}
# Create 'impl_1_opt_report_drc_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_opt_report_drc_0] "" ] } {
  create_report_config -report_name impl_1_opt_report_drc_0 -report_type report_drc:1.0 -steps opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_opt_report_drc_0]
if { $obj != "" } {

}
# Create 'impl_1_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj

}
# Create 'impl_1_power_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_power_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_power_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps power_opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_power_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj

}
# Create 'impl_1_place_report_io_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_io_0] "" ] } {
  create_report_config -report_name impl_1_place_report_io_0 -report_type report_io:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_io_0]
if { $obj != "" } {

}
# Create 'impl_1_place_report_utilization_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_utilization_0] "" ] } {
  create_report_config -report_name impl_1_place_report_utilization_0 -report_type report_utilization:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_utilization_0]
if { $obj != "" } {

}
# Create 'impl_1_place_report_control_sets_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_control_sets_0] "" ] } {
  create_report_config -report_name impl_1_place_report_control_sets_0 -report_type report_control_sets:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_control_sets_0]
if { $obj != "" } {

}
# Create 'impl_1_place_report_incremental_reuse_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_incremental_reuse_0] "" ] } {
  create_report_config -report_name impl_1_place_report_incremental_reuse_0 -report_type report_incremental_reuse:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_incremental_reuse_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj

}
# Create 'impl_1_place_report_incremental_reuse_1' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_incremental_reuse_1] "" ] } {
  create_report_config -report_name impl_1_place_report_incremental_reuse_1 -report_type report_incremental_reuse:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_incremental_reuse_1]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj

}
# Create 'impl_1_place_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_place_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj

}
# Create 'impl_1_post_place_power_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_post_place_power_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_post_place_power_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps post_place_power_opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_post_place_power_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj

}
# Create 'impl_1_phys_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_phys_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_phys_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps phys_opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_phys_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj

}
# Create 'impl_1_route_report_drc_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_drc_0] "" ] } {
  create_report_config -report_name impl_1_route_report_drc_0 -report_type report_drc:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_drc_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_methodology_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_methodology_0] "" ] } {
  create_report_config -report_name impl_1_route_report_methodology_0 -report_type report_methodology:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_methodology_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_power_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_power_0] "" ] } {
  create_report_config -report_name impl_1_route_report_power_0 -report_type report_power:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_power_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_route_status_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_route_status_0] "" ] } {
  create_report_config -report_name impl_1_route_report_route_status_0 -report_type report_route_status:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_route_status_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_route_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_timing_summary_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_incremental_reuse_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_incremental_reuse_0] "" ] } {
  create_report_config -report_name impl_1_route_report_incremental_reuse_0 -report_type report_incremental_reuse:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_incremental_reuse_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_clock_utilization_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_clock_utilization_0] "" ] } {
  create_report_config -report_name impl_1_route_report_clock_utilization_0 -report_type report_clock_utilization:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_clock_utilization_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_bus_skew_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_bus_skew_0] "" ] } {
  create_report_config -report_name impl_1_route_report_bus_skew_0 -report_type report_bus_skew:1.1 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_bus_skew_0]
if { $obj != "" } {

}
# Create 'impl_1_post_route_phys_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_post_route_phys_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_post_route_phys_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps post_route_phys_opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_post_route_phys_opt_report_timing_summary_0]
if { $obj != "" } {

}
# Create 'impl_1_post_route_phys_opt_report_bus_skew_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_post_route_phys_opt_report_bus_skew_0] "" ] } {
  create_report_config -report_name impl_1_post_route_phys_opt_report_bus_skew_0 -report_type report_bus_skew:1.1 -steps post_route_phys_opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_post_route_phys_opt_report_bus_skew_0]
if { $obj != "" } {

}
set obj [get_runs impl_1]
set_property -name "needs_refresh" -value "1" -objects $obj
set_property -name "strategy" -value "Vivado Implementation Defaults" -objects $obj
set_property -name "steps.write_bitstream.args.readback_file" -value "0" -objects $obj
set_property -name "steps.write_bitstream.args.verbose" -value "0" -objects $obj

# set the current impl run
current_run -implementation [get_runs impl_1]

puts "INFO: Project created:${_xil_proj_name_}"
